@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container_Ext(master1,"Master","Faz interface com o usuário, executado no Laptop")
Container_Ext(motordriver1,"Motor Driver","Controlador de movimento e I/O de dispositivos eletrônicos, executado num Teknic ClearCore.")


Container_Boundary(robot_context,"Lego Robot Container"){
    Component(statusUpdater,"Status Updater","C++ class")
    Component(robot,"Robot","C++ class")
    Component(robotServer,"Robot Server","C++ class")
    Component(trayController,"Tray Controller","C++ class")
    Component(marvelmindWrapper,"Marvelmind Wrapper","C++ class")
    Component(cameraTracker,"Camera Tracker","C++ class")
    Component(robotController,"Robot Controller","C++ class")

    Rel(robot,trayController," Controla ", )

    Rel(robot,robotController," Controla ")

    Rel_U(robot,statusUpdater,"Mantém o Status e o retorna ")

    Rel_R(robot,cameraTracker," Recebe imagens do  ")

    Rel_L(robot,marvelmindWrapper," Recebe posições do ")


}



BiRel(master1,robotServer," Robô envia dados e Master envia comandos ")


BiRel(robotServer,robot," Troca informações")


Rel(robotController,motordriver1," Controla a movimentação")


Rel(trayController,motordriver1," Controla o colocamento de dominós")





@enduml












