@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Boundary(robot_context,"Robot Context"){
    
    Component(statusUpdater,"Status Updater")
    Component(robotServer,"Robot Server")
    Component(trayController,"Tray Controller")
    Component(marvelmindWrapper,"Marvelmind Wrapper")
    Component(cameraTracker,"Camera Tracker")
    Component(robotController,"Robot Controller")
    
    
}




@enduml