@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml



System_Boundary(server,"Servidor"){
    Person(user,"Usuário burro")
    System(server1,"Servidor")

    Rel(user,server1,"Usa")
    Rel(user,server1,"Monitora")
    Rel(user,server1,"Controla")
}

System_Boundary(client,"Cliente"){
    Person(user2,"Usuário burro")
    System(robot2,"Robô do Lego")

    Rel(user2,robot2,"Usa")
    Rel(user2,robot2,"Monitora")
    Rel(user2,robot2,"Controla")
}

Rel(server1,robot2,"Controla")



@enduml